name: jeepneyfornoobs_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  http: 0.13.6
  shared_preferences: ^2.5.1
  lottie:
  hidden_drawer_menu: ^3.0.1
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^2.0.9
  curved_navigation_bar: ^1.0.3
  google_maps_flutter: ^2.10.0
  sliding_up_panel: ^2.0.0+1
  flutter_polyline_points: ^1.0.0
  location: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/apple.png
    - lib/assets/google_logo.png
    - lib/assets/login_bg.png
    - lib/assets/triangle-overlay.png
    - lib/assets/startup.json
    - lib/assets/jeepney.svg
    - lib/assets/maps.png
